version: '3.1'

services:

  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: database
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456
    ports:
      - 3306:3306